baseURL = "http://example.org/"
languageCode = "en-us"
title = "Delta Sec"
theme = "forty"

googleAnalytics = ""

[params]
  name = "Dimitrios Stergiou"
  description = "Your description"
  custom_css = []
  custom_js  = []
  favicon    = "img/favicon.ico"
  image = ""

  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  [params.navigation]
    title = "Home"
    #subtitle = "Risk and Security consulting services"
    menu = "Menu"
    # Optional logo as brand stored in img/
    # logo = "logo.png"

   [[params.navigation.links]]
      name = "About Delta Sec"
      url = "company/about"

    [[params.navigation.button1]]
      name = "Home"
      url = "#"

    [[params.navigation.links]]
      name = "Information Security"
      url = "services/infosec"

    [[params.navigation.links]]
      name = "Privacy (GDPR)"
      url = "services/privacy"

    [[params.navigation.links]]
      name = "Vulnerability Assessement"
      url = "services/vulnerability"

    [[params.navigation.links]]
      name = "iGaming Security"
      url = "services/igaming"

    [[params.navigation.links]]
      name = "Secure Development (SDLC)"
      url = "services/sdlc"

    [[params.navigation.links]]
      name = "Awareness Training"
      url = "services/training"

    [[params.navigation.links]]
      name = "Risk Management"
      url = "services/risk"

    [[params.navigation.links]]
      name = "Speaking engagements"
      url = "services/conference"

  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "Delta Sec"
    subtitle = "Risk, Privacy, and Security consulting services"
    buttonText = "Our services"

  [params.tiles]
    enable = true
    
    [[params.tiles.showcase]]
      title = "Privacy (GDPR)"
      subtitle = "GDPR Compliance and Privacy Services"
      image = "services/privacy.jpg"
      url = "services/privacy"

    [[params.tiles.showcase]]
      title = "Information Security"
      subtitle = "Cyber and Information Security Services"
      image = "services/security.jpg"
      url = "services/infosec"

    [[params.tiles.showcase]]
      title = "Vulnerability assessment"
      subtitle = "Assess how your external assets appear to a potential attacker"
      image = "services/vulnerability.jpg"
      url = "services/vulnerability"
    
    [[params.tiles.showcase]]
      title = "Secure Software Development"
      subtitle = "Secure Engineering Principles and SDLC"
      image = "services/sdlc.jpg"
      url = "services/sdlc"
    
    [[params.tiles.showcase]]
      title = "Cyber Security Awareness"
      subtitle = "Awareness training focusing on Social Engineering"
      image = "services/awareness.jpg"
      url = "services/training"

    [[params.tiles.showcase]]
      title = "iGaming Security Services"
      subtitle = "Regulatory compliance for iGaming"
      image = "services/igaming.jpg"
      url = "services/igaming"

    [[params.tiles.showcase]]
      title = "Risk management"
      subtitle = "Build your Enterprise Risk Management framework"
      image = "services/risk.jpg"
      url = "services/risk"

    [[params.tiles.showcase]]
      title = "Speaker and presenter"
      subtitle = "Do you need a speaker for your next conference?"
      image = "services/conference.jpg"
      url = "services/conference"
  
  [params.blog]
  # Section Type Two
  [params.two]
    enable = true
    title = "About Delta Sec"
    subtitle = """Delta Sec is a consulting company that offers services in the areas of
    Information Security, Privacy and Security Awarness Training. If you want to learn more
    about the company follow this link."""
    buttonText = "About us"
    url = "company"

  # Contact section
  [params.contact]
    enable = false
    buttonSend = "Send message"
    buttonClear = "Clear"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below and uncomment
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    # formEmail = "example@domain.com"

    # Contact Section
    # You can add multiple emails, phone numbers, or addresses
    # by copying the corresponding map with frontmatter code.
    [[params.contact.email]]
    title = "Email"
    email = "dstergiou@gmail.com"

    [[params.contact.phone]]
    title = "Phone"
    phone = "+ 46 73699 2725"

    [[params.contact.address]]
    title = "Address"
    street = "Tegelviksgatan 41"
    city = "Stockholm, 11641"
    country = "Sweden"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Delta Sec 2018"

    [[params.footer.social]]
      icon = "fa-envelope"
      url= "mailto:dstergiou@gmail.com"
      label = "Email"

    [[params.footer.social]]
      icon = "fa-mobile"
      url= "tel:+46736992725"
      label = "Phone"
    
    [[params.footer.social]]
      icon = "fa-whatsapp"
      url= "https://api.whatsapp.com/send?phone=46736992725"
      label = "WhatsApp"

    [[params.footer.social]]
      icon = "fa-twitter"
      url= "https://www.twitter.com/dstergiou"
      label = "Twitter"

    [[params.footer.social]]
      icon = "fa-linkedin"
      url= "https://www.linkedin.com/in/dstergiou/"
      label = "LinkedIn"