baseURL = "http://example.org/"
languageCode = "en-us"
title = "Delta Security"
theme = "forty"

googleAnalytics = ""

[params]
  name = "Dimitrios Stergiou"
  description = "Your description"
  custom_css = []
  custom_js  = []
  favicon    = "img/favicon.ico"
  image = ""

  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  [params.navigation]
    title = "Home"
    #subtitle = "Risk and Security consulting services"
    #menu = "Menu"
    # Optional logo as brand stored in img/
    # logo = "logo.png"

    [[params.navigation.button1]]
      name = "Home"
      url = "#"

    [[params.navigation.links]]
      name = "Privacy (GDPR)"
      url = "blogs/privacy"

    [[params.navigation.links]]
      name = "Information Security"
      url = "blogs/infosec"

    [[params.navigation.links]]
      name = "Secure Development (SDLC)"
      url = "blogs/sdlc"

    [[params.navigation.links]]
      name = "iGaming Security"
      url = "blogs/igaming"

    [[params.navigation.links]]
      name = "Awareness Training"
      url = "blogs/training"

    [[params.navigation.links]]
      name = "Speaking engangements"
      url = "blogs/conference"

    [[params.navigation.links]]
      name = "About Delta Security"
      url = "blogs/about"


  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "Delta Security"
    subtitle = "Risk, Privacy, and Security consulting services"
    buttonText = "Our services"

  [params.tiles]
    enable = true
    
    [[params.tiles.showcase]]
      title = "Privacy (GDPR)"
      subtitle = "Ipsum Dolor Sit Amet"
      image = "privacy.jpg"
      url = "blogs/privacy"

    [[params.tiles.showcase]]
      title = "Information Security"
      subtitle = "Feugiat Amet Tempus"
      image = "security.jpg"
      url = "blogs/infosec"

    [[params.tiles.showcase]]
      title = "Secure Application Development"
      subtitle = "Lorem Etiam Nullam"
      image = "sdlc.jpg"
      url = "blogs/sdlc"

    [[params.tiles.showcase]]
      title = "iGaming Security Services"
      subtitle = "Nisl Sed Aliquam"
      image = "igaming.jpg"
      url = "blogs/igaming"

    [[params.tiles.showcase]]
      title = "Cyber Security Awareness"
      subtitle = "Ipsum Dolor Sit Amet"
      image = "awareness.jpg"
      url = "blogs/training"

    [[params.tiles.showcase]]
      title = "Speaker and presenter"
      subtitle = "Feugiat Amet Tempus"
      image = "conference.jpg"
      url = "blogs/conference"
  
  [params.blog]

  # Section Type Two
  [params.two]
    #enable = true
    #title = "About Delta Security"
    #subtitle = """Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero. 
    #Mauris aliquet magna magna sed nunc rhoncus pharetra. 
    #Pellentesque condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia pellentesque lorem ipsum dolor. 
    #Nullam et orci eu lorem consequat tincidunt. Vivamus et sagittis libero.
    #Mauris aliquet magna magna sed nunc rhoncus amet pharetra et feugiat tempus."""
    #buttonText = "Get Started"
    #url = "blogs"

  # Contact section
  [params.contact]
    enable = false
    buttonSend = "Send message"
    buttonClear = "Clear"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below and uncomment
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    # formEmail = "example@domain.com"

    # Contact Section
    # You can add multiple emails, phone numbers, or addresses
    # by copying the corresponding map with frontmatter code.
    [[params.contact.email]]
    title = "Email"
    email = "dstergiou@gmail.com"

    [[params.contact.phone]]
    title = "Phone"
    phone = "+ 46 73699 2725"

    [[params.contact.address]]
    title = "Address"
    street = "Tegelviksgatan 41"
    city = "Stockholm, 11641"
    country = "Sweden"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Delta Security 2018"

    [[params.footer.social]]
      icon = "fa-envelope"
      url= "mailto:dstergiou@gmail.com"
      label = "Email"

    [[params.footer.social]]
      icon = "fa-twitter"
      url= "https://www.twitter.com/dstergiou"
      label = "Twitter"

    [[params.footer.social]]
      icon = "fa-linkedin"
      url= "https://www.linkedin.com/in/dstergiou/"
      label = "LinkedIn"